# Useful docs:
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Bug Report
description: File a bug report
# title: "[Bug]: "
labels: ["bug", "triage"]
# projects: ["octo-org/1", "octo-org/44"]
#assignees:
#  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: package
    attributes:
      label: Package containing the bug
      description: What package in this monorepo has the bug?
      options:
        - I’m not sure
        - next (Drupal module)
        - next-drupal (NPM package)
        - basic-starter
        - graphql-starter
        - example-auth
        - example-blog
        - example-client
        - example-custom-auth
        - example-custom-cache
        - example-custom-fetcher
        - example-custom-serializer
        - example-graphql
        - example-marketing
        - example-query
        - example-search-api
        - example-umami
        - example-webform
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      # placeholder: Tell us what you see!
      # value: ""
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      # placeholder: Tell us what you see!
      value: |
        ## Steps to reproduce:

        1. First '...'
        2. Then '....'
        3. 😢

        If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
